 <div class="mainbar">
        <div class="article">
          <h2>a<span>K</span>tel Zone</h2>        
          <img src="<?php echo $this->baseUrl(); ?>/images/education.jpg" width="209"   alt="image"  class="fl" />
          <p>e<span style="color: red; font: bold">X</span>cellerate is a Training  and Learning management Portal which provides organizations with a powerful eLearning platform that integrates seamlessly with  live broadcast.  <p>e<span style="color: red ; font: bold">X</span>cellerate  is a web based delivery of training content, tutorials, white papers, presentations etc which can be accessed by the employee anytime and anywhere.
          </p><p> <p>e<span style="color: red ; font: bold">X</span>cellerate  provide provision of a 24X7 training and development model for employees/student .
            <p>e<span style="color: red; font: bold" >X</span>cellerate enable an organization to effectively trained a large group of individuals spread across the organization.
            <p>e<span style="color: red; font: bold">X</span>cellerate provide virtual learning environment and our Current thinking is that the LMS will become like Google</p>
        </div>   
       <div class="article">
           
          <h2>Features  Of a<span>k</span>tel</h2> 
           <p class="infopost">  <a href="#" class="com"><span>11</span></a></p>    
             
           <ul>
             <li style="list-style: circle">Contain Management System.</li>
             <li style="list-style: circle">Course Management.</li>
             <li style="list-style: circle">User Management System</li>
             <li style="list-style: circle">Module Configuration.</li>              
             <li style="list-style: circle">Social Learning Facilities through forum, Chat ,Blog etc.</li>
             <li style="list-style: circle">Online grading tool, Testing and Scoring engine , Assignments, Quizzes Certification and Many More.</li>
             <li style="list-style: circle">Collaboration Tools Like white Board ,Real Time Broadcast. and many more...!</li>
          </ul>
 </div>  
 </div>