 <div class="administrator_head"><a href="#" class="active">+ Right Now</a></div>
<div id="AdminNotificationdiv" style="display: none;" >
      <table cellspacing="0"  class="fbtable">
                    <tr>
                    <td>
                      <?php echo $this->rightnow; ?> 
                    </td>
                    </tr>
            </table>
 </div>
 
 <!-- dasbord start  -->
<div style="display: none;" class="report">    
<div class="administrator_head" ><a href="#" class="active">+Dashboard</a></div>
 <div class="report1">
 <img alt="" src="/skin/adminhtml/default/default/images/report.png">
 </div> 
 <div class="report2"><img alt="" src="/skin/adminhtml/default/default/images/report2.jpg" /></div>
    
    

<div class="administrator_head"><a href="#" class="active">+End</a></div>
</div>
 
 <!-- dasbord end  -->
 
  <!-- club start  -->
 <div class="club" >
 
 	<ul class="row" >
 		<li  class="col"><a href="" > <img src="/skin/adminhtml/default/default/images/users.png" /></a></li>
 	    <li  class="col"><a href="" > <img src="/skin/adminhtml/default/default/images/users.png" /> </a></li>
 	    <li  class="col"><a href="" > <img src="/skin/adminhtml/default/default/images/users.png" /> </a></li>
 	    <li  class="col"><a href="" > <img src="/skin/adminhtml/default/default/images/users.png" /> </a></li>
 	    <li  class="col"><a href="" > <img src="/skin/adminhtml/default/default/images/users.png" /> </a></li>
 	    <li  class="col"><a href="" > <img src="/skin/adminhtml/default/default/images/users.png" /> </a></li>
 	    <li  class="col"><a href="" > <img src="/skin/adminhtml/default/default/images/users.png" /> </a></li>
 	    <li  class="col"><a href="" > <img src="/skin/adminhtml/default/default/images/users.png" /> </a></li>
 	    <li  class="col"><a href="" > <img src="/skin/adminhtml/default/default/images/users.png" /> </a></li>
 	    <li  class="col"><a href="" > <img src="/skin/adminhtml/default/default/images/users.png" /> </a></li>
 	    <li  class="col"><a href="" > <img src="/skin/adminhtml/default/default/images/users.png" /> </a></li>
 	    <li  class="col"><a href="" > <img src="/skin/adminhtml/default/default/images/users.png" /> </a></li>
 	    <li  class="col"><a href="" > <img src="/skin/adminhtml/default/default/images/users.png" /> </a></li>
 	    <li  class="col"><a href="" > <img src="/skin/adminhtml/default/default/images/users.png" /> </a></li>
 	    <li  class="col"><a href="" > <img src="/skin/adminhtml/default/default/images/users.png" /> </a></li>
 	    <li  class="col"><a href="" > <img src="/skin/adminhtml/default/default/images/users.png" /> </a></li>
 	    <li  class="col"><a href="" > <img src="/skin/adminhtml/default/default/images/users.png" /> </a></li>
 	    <li  class="col"><a href="" > <img src="/skin/adminhtml/default/default/images/users.png" /> </a></li>
 	    <li  class="col"><a href="" > <img src="/skin/adminhtml/default/default/images/users.png" /> </a></li>
 	    
 	</ul>
 
 </div>
       