<div id="message-yellow">
				<table border="0" width="100%" cellpadding="0" cellspacing="0">
				<tbody><tr>
					<td class="yellow-left">You have a new message. <a href="">Go to Inbox.</a></td>
					<td class="yellow-right"><a class="close-yellow"><img src="/skin/frontend/default/apps1/images/table/icon_close_yellow.gif" alt=""></a></td>
				</tr>
				</tbody></table>
 </div>
				


<div class="administrator_head"><a href="#" class="active">+ Add Course</a></div>
 		<div id="database_backup" >
		   <div id="formdiv"> 
               <div class="Add_Course"  >
                  <?php  echo $this->addcourseForm; ?>
			  </div>
			</div>
          </div>     
                          
 <div class="administrator_head"><a href="#" class="active">+ Course Back Up</a></div>
 