
<div id="message-green">
				<table border="0" width="100%" cellpadding="0" cellspacing="0">
				<tbody><tr>
					<td class="green-left"><?php echo $this->listCourse; ?>. <a href="">Add new one.</a></td>
					<td class="green-right"><a class="close-green"><img src="/skin/frontend/default/apps1/images/table/icon_close_green.gif" alt=""></a></td>
				</tr>
				</tbody>
				</table>
 </div>

				
<div class="administrator_head"><a href="#" class="active">+ List</a></div>

		<div class="request">
					
			       
			        <div id="content-table-inner">
						 
										<table border="0" width="100%" cellpadding="0" cellspacing="0" id="product-table">
										<tr>
											<th class="table-header-check"><a id="toggle-all" ></a> </th>
											<th class="table-header-repeat line-left minwidth-1"><a href="">Course Name</a>	</th>
											<th class="table-header-repeat line-left minwidth-1"><a href="">Cotegry</a></th>
											<th class="table-header-repeat line-left"><a href="">Email</a></th>
											<th class="table-header-repeat line-left"><a href="">Due</a></th>
											<th class="table-header-repeat line-left"><a href="">Website</a></th>
											<th class="table-header-options line-left"><a href="">Options</a></th>
										</tr>
										<tr>
											<td><input  type="checkbox"/></td>
											<td>Sabev</td>
											<td>George</td>
											<td><a href="">george@mainevent.co.za</a></td>
											<td>R250</td>
											<td><a href="">www.mainevent.co.za</a></td>
											<td class="options-width">
											<a href="" title="Edit" class="icon-1 info-tooltip"></a>
											<a href="" title="Edit" class="icon-2 info-tooltip"></a>
											<a href="" title="Edit" class="icon-3 info-tooltip"></a>
											<a href="" title="Edit" class="icon-4 info-tooltip"></a>
											<a href="" title="Edit" class="icon-5 info-tooltip"></a>
											</td>
										</tr>
										<tr class="alternate-row">
											<td><input  type="checkbox"/></td>
											<td>Sabev</td>
											<td>George</td>
											<td><a href="">george@mainevent.co.za</a></td>
											<td>R250</td>
											<td><a href="">www.mainevent.co.za</a></td>
											<td class="options-width">
											<a href="" title="Edit" class="icon-1 info-tooltip"></a>
											<a href="" title="Edit" class="icon-2 info-tooltip"></a>
											<a href="" title="Edit" class="icon-3 info-tooltip"></a>
											<a href="" title="Edit" class="icon-4 info-tooltip"></a>
											<a href="" title="Edit" class="icon-5 info-tooltip"></a>
											</td>
										</tr> 
										</table>  
									 
									 <div id="actions-box">
										<a href="" class="action-slider"></a>
										<div id="actions-box-slider">
											<a href="" class="action-edit">add</a>
											<a href="" class="action-edit">Edit</a>
											<a href="" class="action-delete">Delete</a>
										</div>
										<div class="clear"></div>
									</div>
									 
									 <table border="0" cellpadding="0" cellspacing="0" id="paging-table">
									<tr>
									<td>
										<a href="" class="page-far-left"></a>
										<a href="" class="page-left"></a>
										<div id="page-info">Page <strong>1</strong> / 15</div>
										<a href="" class="page-right"></a>
										<a href="" class="page-far-right"></a>
									</td>
									<td>
									<select  class="styledselect_pages">
										<option value="">Number of rows</option>
										<option value="">1</option>
										<option value="">2</option>
										<option value="">3</option>
									</select>
									</td>
									</tr>
									</table>
									 
									<div class="clear"></div>
								 
								</div>
								 
							<div class="clear">&nbsp;</div>
			 		
		</div>
  

<div class="administrator_head"><a href="#" class="active">+ Client</a></div>
   