<div class="content">
        <div class="content_resize">
            


<div class="mainbar"> 
             
                                                                                                          
                                                                                                        
            <div align="center" style="padding-top: 20px;">
                            <table cellspacing="0" class="lefttable" id="CourseSearchEnginetb">
                            <tbody><tr>
                                <td width="98%" height="21" bgcolor="#D8DFEA" colspan="3" class="fbtab">+ Course Search Engine</td>
                            </tr>
                             </tbody>
                            </table>
                <form id="customForm" action="" method="get">	 
                    <input type="text" onblur="if(this.value==''){this.value='Enter Course name';}" onfocus="if(this.value=='Enter Course name'){this.value='';}" value="Enter Course name" size="50" id="testinput" name="text" width:200px="">
                    <input type="submit" class="wb_button" value="Search">
                </form>
                <hr style="color: #003366">
            </div>
                                                                                                                        <table cellspacing="0" class="lefttable" id="tb">
                                                                                                                <tbody><tr>
                                                                                                                    <td width="98%" height="21" bgcolor="#D8DFEA" colspan="3" class="fbtab">+ Search Result</td>
                                                                                                                </tr>
                                                                                                            </tbody></table>
                                                                                                                    <!--        <table  cellspacing="0" cellpadding="2" style="margin-top: 10px"> -->

                                               <div id="clubtabdv">              
                                <table cellspacing="0" class="fbtable">
                                    <tbody><tr>
                                        <td>  
                                     
                                      <div class="list-root border-radius">
                                                <div class="in1">
                                                    <div class="in2">
                                                        <div class="list">
                                                            <div class="photo fl"><a href="Course/index.php?94a08da1fecbb6e8b46990538c7b50b2=64186f9bae22841257493633858f4927&amp;dd395d6201581ad212d782d571f0ad64=25"><img width="50px" height="50px" alt="" src="images/icon/emblem_library.png" id="title"></a></div>
                                                             <span class="posted">Course Name: <a href="Course/index.php?94a08da1fecbb6e8b46990538c7b50b2=64186f9bae22841257493633858f4927&amp;dd395d6201581ad212d782d571f0ad64=25">Chemistry</a></span><span class="posted">Author :Instructor</span> 
                                                            <div class="data">
                                                                <p>Chemistry </p>
                                                             </div>                                                     
                                                        </div>  
                                                    </div> 
                                                </div>  
                                            </div>
 
                             
                                      <div class="list-root border-radius">
                                                <div class="in1">
                                                    <div class="in2">
                                                        <div class="list">
                                                            <div class="photo fl"><a href="Course/index.php?94a08da1fecbb6e8b46990538c7b50b2=64186f9bae22841257493633858f4927&amp;dd395d6201581ad212d782d571f0ad64=32"><img width="50px" height="50px" alt="" src="images/icon/emblem_library.png" id="title"></a></div>
                                                             <span class="posted">Course Name: <a href="Course/index.php?94a08da1fecbb6e8b46990538c7b50b2=64186f9bae22841257493633858f4927&amp;dd395d6201581ad212d782d571f0ad64=32">IBM MainFrame Work</a></span><span class="posted">Author :Instructor</span> 
                                                            <div class="data">
                                                                <p>course </p>
                                                             </div>                                                     
                                                        </div>  
                                                    </div> 
                                                </div>  
                                            </div>
 
                             
                                      <div class="list-root border-radius">
                                                <div class="in1">
                                                    <div class="in2">
                                                        <div class="list">
                                                            <div class="photo fl"><a href="Course/index.php?94a08da1fecbb6e8b46990538c7b50b2=64186f9bae22841257493633858f4927&amp;dd395d6201581ad212d782d571f0ad64=22"><img width="50px" height="50px" alt="" src="images/icon/emblem_library.png" id="title"></a></div>
                                                             <span class="posted">Course Name: <a href="Course/index.php?94a08da1fecbb6e8b46990538c7b50b2=64186f9bae22841257493633858f4927&amp;dd395d6201581ad212d782d571f0ad64=22">Hindi</a></span><span class="posted">Author :Instructor</span> 
                                                            <div class="data">
                                                                <p>Hindi </p>
                                                             </div>                                                     
                                                        </div>  
                                                    </div> 
                                                </div>  
                                            </div>
 
                             
                                      <div class="list-root border-radius">
                                                <div class="in1">
                                                    <div class="in2">
                                                        <div class="list">
                                                            <div class="photo fl"><a href="Course/index.php?94a08da1fecbb6e8b46990538c7b50b2=64186f9bae22841257493633858f4927&amp;dd395d6201581ad212d782d571f0ad64=30"><img width="50px" height="50px" alt="" src="images/icon/course_icon.jpg" id="title"></a></div>
                                                             <span class="posted">Course Name: <a href="Course/index.php?94a08da1fecbb6e8b46990538c7b50b2=64186f9bae22841257493633858f4927&amp;dd395d6201581ad212d782d571f0ad64=30">Physics Part - II</a></span><span class="posted">Author :Instructor</span> 
                                                            <div class="data">
                                                                <p>sasasas </p>
                                                             </div>                                                     
                                                        </div>  
                                                    </div> 
                                                </div>  
                                            </div>
 
                               </td></tr>
                                </tbody></table>
                            </div> 
</div>
        </div>
                                                                                                            <script>
                                                                                                            $("#CourseSearchEnginetb").click(function () {
                                                                                                                $("#CourseSearchEnginedv").slideToggle("slow");
                                                                                                            });
                                                                                                            </script>

                                                                                                                    </div>