<div class="administrator_sidebar_content">

		 
		<div class="administrator_tab"><a href="/admin/club">Club</a></div>		
		<div class="administrator_tab"><a href="/admin/course" class="active">Course</a></div>
		<div class="administrator_tab"><a href="/admin/exam">Exam</a></div>
		<div class="administrator_tab"><a href="/admin/users">Users</a></div> 
		<div class="administrator_tab"><a href="/admin/report">Report</a></div>
		<div class="administrator_tab"><a href="/admin/log">logs</a></div>		 
		<div class="administrator_tab"><a href="/admin/backup">Practish Paper</a></div>
		<div class="administrator_tab"><a href="/admin/assingment">Assingment</a></div>
		<div class="administrator_tab"><a href="/admin/SEO">SEO</a></div>
		<div class="administrator_tab"><a href="/admin/backup">Report</a></div>
		<div class="administrator_tab"><a href="/admin/backup">Privecy</a></div>
		



</div>