<div class="content">
                <div class="content_resize">
                    <div class="mainbar"> 
                        <div id="Containt" class="containt" align="center">
                            <table cellspacing="0" class="fbtable">
                                <tbody><tr>
                                    <td bgcolor="#D8DFEA" class="fbtab" height="21" width="98%" colspan="3">+ My Profile</td>
                                </tr>
                            </tbody></table>
                            <div>
                                <table cellspacing="0" class="fbtable">
                                    <tbody><tr>
                                        <td>
                                            <form action="#">
                                                <div class="fbinfobox" style="width: 97%"><a href="#">Personal Details</a></div>
                                                <table width="100%" cellpadding="3">
                                                    <tbody><tr>
                                                        <td width="127" valign="top"><img style="margin-left: 20px;" src="../Profileimage//347355.jpg" class="profile-img"></td>
                                                        <td width="393" valign="top">
                                                            <table width="385" cellpadding="3">

                                                                <tbody><tr>
                                                                    <td width="171">Full Name</td>
                                                                    <td width="194"><em>Instructor</em></td>
                                                                </tr>
                                                                <tr>
                                                                    <td>&nbsp;</td>
                                                                </tr>
                                                                <tr>
                                                                    <td>Gender</td>
                                                                    <td><a href="#">male</a></td>
                                                                </tr> 
                                                                <tr>
                                                                    <td>Date Of Birth</td>
                                                                    <td><a href="#">1990-02-10</a></td>
                                                                </tr> 
                                                                <tr>
                                                                    <td>Status</td>
                                                                    <td>   </td>
                                                                </tr>
                                                                <tr>
                                                                    <td>Registration Date</td>
                                                                    <td> 2011-09-10 13:23:27 </td>
                                                                </tr>


                                                            </tbody></table>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td colspan="2"><div class="fbinfobox" style="width: 97%"><a href="#">Contact Details</a></div></td>
                                                    </tr>

                                                    <tr> <td width="127" valign="top">  </td>
                                                        <td width="393" valign="top">
                                                            <table width="100%">
                                                                <tbody>

                                                                    <tr>
                                                                        <th width="25%"></th>
                                                                        <td width="75%">
                                                                                                                                            </td></tr><tr>
                                                                            <td>Email</td>
                                                                            <td><a href="mailto:vsaurabh.aec@gmail.com">vsaurabh.aec@gmail.com</a></td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td>Phone No</td>
                                                                            <td> 9958968054</td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td>Address</td>
                                                                            <td> 187 sctor 20 noida new delhi</td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td>From</td>
                                                                            <td> INDIA</td>
                                                                        </tr>
             
                                                                    
                                                                    
                                                                </tbody>
                                                            </table>
                                                        </td>
                                                    </tr>
                                                    <tr>

                                                        <td colspan="2"><div class="fbinfobox" style="width: 97%">Attendance report</div></td>
                                                    </tr>

                                                    <tr>  
                                                        <td width="127" valign="top">  </td>
                                                        <td width="393" valign="top">
                                                            <table width="100%">
                                                                <tbody>

                                                                    <tr>
                                                                        <td>Course Attendance</td>
                                                                        <td>148 </td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td>Club Attendance</td>
                                                                        <td> 78</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td>Profile Login</td>
                                                                        <td>76</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td>Proficiency</td>
                                                                        <td> 0</td>
                                                                    </tr>

                                                                </tbody>
                                                            </table> 
                                                        </td>

                                                    </tr>
                                                    <tr>
                                                        <td colspan="2"><div class="fbinfobox" style="width: 97%">Course&amp;Club</div></td>
                                                    </tr>

                                                    <tr>  
                                                        <td width="127" valign="top">  </td>
                                                        <td width="393" valign="top">
                                                            <table width="100%">
                                                                <tbody>

                                                                    <tr>
                                                                                    <td>Course</td>
                                                                        <td><ul><marquee onmouseover="stop();" onmouseout="start();"><marquee> </marquee></marquee></ul></td>
                                                                                        </tr>
                                                                                        <tr>
                                                                                                        <td>Clubs</td>
                                                                                            <td>  <ul><marquee onmouseover="stop();" onmouseout="start();"><marquee> 
                                                                                                            </marquee></marquee></ul></td>
                                                                                                            </tr>


                                                                                                            </tbody>
                                                                                                            </table> 
                                                                                                            </td>

                                                                                                            </tr>
                                                                                                            </tbody></table>
                                                                                                                                                                                                                        <br>

                                                                                                            </form>
                                                                                                            </td></tr>
                                                                                                            </tbody></table>
                                                                                                            </div>
                                                                                                            </div>
                                                                                                            </div>


  
    </div>
  </div>