 <div class="mainbar">  
    <table cellspacing="0" id="UserNameandPasswordtb"  class="lefttable">
       <tr  >
    <td bgcolor="#D8DFEA" class="fbtab" height="21" width="98%" colspan="3"  ><a href="#">+ Enabling our Customers</a></td>
       </tr>
    </table>
            
    <div id="UserNameandPassworddv">
                  <table cellspacing="0"  class="lefttable">
                    <tr>
                    <td>
                        <p>
                           sack Is a CMMI Level 3 Company that has been providing high-quality software solutions to our customers since1999 </p>
                        </p><p> We at sack understand the culture, demanding business issues, processes and procedures, architecture and administrative requirements within our clients.
                  <p>  The sack team experienced technical specialist and consultants have the knowledge and expertise to argument teams and deliver on reqirements.</p>
                    We provide the Small-Medium Enterprise (SME) and Fortune 500 clients, worldwide, with platform independent standards, complaint frameworks and components, and CMMI Level 3 assessed software development services. sack also offers flexible on-site, off-site and off-shore capabilities to accommodate the client's needs

                   </td>
                    </tr>
                </table>
     </div>
    
     </div> 