<div class="flash-position"><object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,19,0" width="960" height="322">
          <param name="movie" value="<?php echo $this->baseUrl(); ?>/swfs/1.swf" />
          <param name="quality" value="high" />
		  <param name="wmode" value="transparent"> 
          <embed src="<?php echo $this->baseUrl(); ?>/swfs/1.swf" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" width="960" height="322" wmode="transparent" ></embed>
        </object>
 </div>