<div class="fbg_resize">
                <div class="col c1">

                    <h2>Course</h2>

                    <a href="#"><img  src="<?php echo $this->baseUrl() ?>/images/pix1.jpg"  width="58" height="58" alt="Hindi" title="Hindi" /></a>
                 
                    <a href="#"><img  src="<?php echo $this->baseUrl() ?>/images/pix1.jpg"  width="58" height="58" alt="Chemistry" title="Chemistry" /></a>
                 
                    <a href="#"><img  src="<?php echo $this->baseUrl() ?>/images/pix1.jpg"  width="58" height="58" alt="Physics Part - II" title="Physics Part - II" /></a>
                 
                    <a href="#"><img  src="<?php echo $this->baseUrl() ?>/images/pix1.jpg"  width="58" height="58" alt="IBM MainFrame Work" title="IBM MainFrame Work" /></a>
                 
                    <a href="#"><img  src="<?php echo $this->baseUrl() ?>/images/pix1.jpg"  width="58" height="58" alt="IBM MainFrame Work" title="IBM MainFrame Work" /></a>
                 
                        </div>
                <div class="col c2">
                    <h2>Customer Login</h2>
                    <form id="customForm" method="post" action="<?php echo $this->baseUrl()."/user/index"; ?>" accept-charset="utf-8"    >
                        <div class="TextField">

                            <input type="text" name="user" id="user" class="text" value="Enter User Name" onfocus="if(this.value=='Enter User Name'){ this.value='';}" onblur="if(this.value==''){ this.value='Enter User Name'}"/>
                            <span class="searchform-input-wrapper"> </span> 
                        </div>
                        <div class="Password">
                            <input type="password"  name="password" id="password" class="password" value="*********" onfocus="if(this.value=='*********'){ this.value='';}" onblur="if(this.value==''){ this.value='*********'}"/>
                        </div>  <div class="searchform-controls">
                            <input type="submit" value="login" id="searchsubmit" class="wb_button">
                        </div>
                        <p><a href="<?php echo $this->baseUrl()."/index/forgetpassword"; ?>">Forgot your password?</a></p>


                    </form>
                </div>
                <div class="col c3">
                    <h2><span>Contact</span></h2>
                    <p> Sack info Pvt. Ltd.<br>
                        A-9 , FM House</br>
                        Sector - 9</br>
                        Noida, Uttar Pradesh</br>
                        201301</br>
                        INDIA </br>
                        Telephone: +0120 4366000</br>
                        Fax: +120 4366098
                    </p>
                </div>
                <div class="clr"></div>
            </div>
            
<!-- <script src="http://ajax.googleapis.com/ajax/libs/dojo/1.7.1/dojo/dojo.js" type="text/javascript"></script> -->

