<div class="gadget">
    <div class="calltoAction">
        <p>
            <img src="<?php echo $this->baseUrl();?>/images/getFree.png" alt="Get Free Consultation" width="178" height="139"></p>
        <p>&nbsp;</p>
        <form action="<?php echo  $this->baseUrl()."/index/freeconsultation" ; ?>" method="post" name="frm" id="frm">
            <input name="name" type="text" id="name" class="textBox1" border="0" value="First Name" onblur="if(this.value==''){ this.value='First Name'}" onclick="if(this.value=='First Name'){this.value=''}">
            <input name="email" type="text" id="email" class="textBox1" border="0" value="Email ID" onblur="if(this.value==''){ this.value='Email ID'}" onclick="if(this.value=='Email ID'){this.value=''}">
            <input name="telephone" type="text" id="telephone" class="textBox1" border="0" value="Phone No." onblur="if(this.value==''){ this.value='Phone No.'}" onclick="if(this.value=='Phone No.'){this.value=''}">
            <input type="submit" class="textBox1" border="0" value="Submit"   style="height:22px; padding:0px; width:178px; cursor:pointer;">
        </form>
    </div>
</div>