<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

        <html xmlns="http://www.w3.org/1999/xhtml">
            <head>                
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
                <link rel="icon" type="images/jpg"  href="/aktel/favicon.jpg" />                 
                <?php echo $this->headLink(); ?>
                <?php echo $this->headScript(); ?>             
                <?php // echo '<script type="text/javascript" src="'.$this->baseUrl().'/js/sack.Js"></script>'; ?>
                
           <?php 	if ($this->dojo()->isEnabled())  { echo $this->dojo();   }

           
           
           ?>
 			
 			
 			
           
           </head>
            <body class="tundra">
                 <div class="main">
                <div class="header">
                    <div class="header_resize">
                            <div class="logo">
                                <h1><a href="/"><span>Aktel</span> LMS <small>end less Energy,Infinite Possibilites </small></a></h1>
                            </div>
                    <div class="menu_nav">
                    	<ul><li><a href="<?php echo $this->baseUrl() ?>/">Home</a></li>
                            <li><a href="<?php echo $this->baseUrl() ?>/index/registration">Registration</a></li>
                            <li><a href="<?php echo $this->baseUrl() ?>/index/search">Course</a></li>
                            <li><a href="#">White Papers</a></li>
                            <li><a href="<?php echo $this->baseUrl() ?>/index/about/">About Aktel</a></li>
                            <li><a href="<?php echo $this->baseUrl() ?>/index/aboutus">About Us</a></li>
                        </ul>
                    </div>
                    <div class="clr"></div>               
                   </div>
                </div> 
                                    
                                    <div id="banner">
                                        <?php echo $this->render('banner.phtml');?>
                                    </div>
                                    <div class="content">
                                            <div class="content_resize">
                                            

                                                <?php echo $this->layout()->content; ?>
                                   
                                   <div class="sidebar">

                                              <?php echo $this->render('sidebar.phtml');?>
                                   </div>
                                        <div class="clr"></div>
                                    </div>
                                 </div>

                     <div class="fbg">
                      
                
               <?php echo $this->render('footer.phtml');?>
                     </div>
        <div class="footer">
            <div class="footer_resize">
                <p class="lf"> &copy; Copyright <a href="#"> sack-ready Solution Pvt Ltd</a>. </p>
                <div class="clr"></div>
            </div>
        </div>
        </div>  
         
        </body>
        </html>

    
 
