<div class="mainbar"> 

    
    <table cellspacing="0" id="UserNameandPasswordtb"  class="lefttable">
       <tr  >
    <td bgcolor="#D8DFEA" class="fbtab" height="21" width="98%" colspan="3"  ><a href="#">+ User Name and Password</a></td>
       </tr>
    </table>
            
    <div id="UserNameandPassworddv">
                  <table cellspacing="0"  class="lefttable">
                    <tr>
                    <td>
                           
                  <?php echo  $this->form;?>
                     </td>
                    </tr>
                </table>
</div>
</div>